version: 0.2

env:
  variables:
    CODE_BUCKET:     quizbattle-code-welf  
    FRONTEND_BUCKET: quizbattle-frontend-welf    

phases:
  install:
    runtime-versions: { python: 3.11 }

  build:
    commands:
      # 1) ZIPs bauen  ─────
      - zip -j register-player-welf-v2.zip register-player-welf/lambda_function.py
      - zip -j submit-answer-welf-v4.zip   submit-answer-welf/lambda_function.py
      - zip -j next-question-welf-v5.zip   next-question-welf/lambda_function.py
      - zip -j send-score-email-welf-v1.zip send-score-email-welf/lambda_function.py 

      # 2) ZIPs nach Code-Bucket kopieren
      - aws s3 cp register-player-welf-v2.zip   s3://$CODE_BUCKET/
      - aws s3 cp submit-answer-welf-v4.zip     s3://$CODE_BUCKET/
      - aws s3 cp next-question-welf-v5.zip     s3://$CODE_BUCKET/
      - aws s3 cp send-score-email-welf-v1.zip  s3://$CODE_BUCKET/

      # 3) Website synchronisieren
      - aws s3 sync website s3://$FRONTEND_BUCKET --delete

artifacts:
  files:
    - register-player-welf-v2.zip
    - submit-answer-welf-v4.zip
    - next-question-welf-v5.zip
    - send-score-email-welf-v1.zip          
    - quizbattle-infra-welf.yaml